### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by alfybe** [jrising/pysoundtouch#2]
Sorry to disturbing for that problem
All was going well till this message
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import soundtouch
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: /usr/local/lib/python2.7/dist-packages/soundtouchmodule.so: undefined symbol: _ZN10soundtouch9BPMDetect12inputSamplesEPKsi

Thanks

**Comment by jrising** [comment]
Hi,

I just ran through the install process on a new machine, and it worked properly for me.  The error you get means that the 'inputSamples' function in the soundtouch library can't be found.  Did you install soundtouch library that is included in the source?  If you had a more recent version of soundtouch, the interface may have changed.

If that doesn't help, please include the output from the soundtouch `make` and `make install` commands.

**Comment by snobordir** [comment]
I actually just barely had this similar problem:

> > > import soundtouch
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: dlopen(/Library/Python/2.7/site-packages/soundtouchmodule.so, 2): Symbol not found: __ZN10soundtouch10SoundTouch17setPitchSemiTonesEf
> > >   Referenced from: /Library/Python/2.7/site-packages/soundtouchmodule.so
> > >   Expected in: flat namespace
> > >  in /Library/Python/2.7/site-packages/soundtouchmodule.so

I'm wondering if my problem is coming from my misunderstanding that lead me to installing soundtouch directly from the soundtouch website before realizing I should have used your version. Once I realized, I just went through the steps again to install your version, but maybe somehow the version I got from the soundtouch website is somehow still causing this? I couldn't figure out the best way to uninstall all the soundtouch stuff to start from scratch. Any tips?

Ps. I've seen people with similar errors altering the ext_modules in setup.py; this have anything to do with it? I saw that you have "ext_modules = [soundtouchmodule]" in your setup. Not really familiar with how this all works. 
https://groups.google.com/forum/#!topic/cython-users/hoxiD1HVLFg
http://stackoverflow.com/questions/7068721/what-is-the-meaning-of-this-importerror-when-importing-a-cython-generated-so-fi

Thanks!

**Comment by jrising** [comment]
It's possible that this error is caused by a difference in the version of the soundtouch library you have installed, but I don't actually think so.  The error says that it can't find the function `SoundTouch::setPitchSemiTones`, which looks to be in both the old version and the new version.  The most likely guess I have is that the soundtouch library that it's finding is not compiled to used integer samples.  Did you compile soundtouch with the command

```
./configure --enable-integer-samples CXXFLAGS="-fPIC"
```

?  You might want to try removing the library entirely, to make sure that it's not finding the other version which was not compiled with that flag.

**Comment by snobordir** [comment]
It's true I didn't have the flags set when I installed SoundTouch directly from their website. I actually attempted to erase that version, but it didn't seem so straightforward. Any advice on how to do that?

Thanks for getting back to me.

**Comment by jrising** [comment]
It would probably be installed into /usr/lib or /usr/local/lib.  But I would actually expect that if you recompile and install the integer version, it will just overwrite the original.  Have you tried that?

**Comment by ssssophiaxd** [comment]
Sorry for bothering, but I recently came across the same problem. I tried everything you mentioned in the previous discussion, and still get this when importing:

> > > > import soundtouch
> > > > Traceback (most recent call last):
> > > >   File "<pyshell#1>", line 1, in <module>
> > > >     import soundtouch
> > > > ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundtouchmodule.so, 2): Symbol not found: __ZN10soundtouch10SoundTouch17setPitchSemiTonesEf
> > > >   Referenced from: /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundtouchmodule.so
> > > >   Expected in: flat namespace
> > > >  in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/soundtouchmodule.so

output of 'make':

> Making all in include
> /Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
> Making all in source
> Making all in SoundTouch
> make[2]: Nothing to be done for `all'.
> Making all in SoundStretch
> make[2]: Nothing to be done for`all'.
> make[2]: Nothing to be done for `all-am'.
> make[1]: Nothing to be done for`all-am'.

output of 'sudo make install':

> Making install in include
> make[2]: Nothing to be done for `install-exec-am'.
>  ../config/install-sh -c -d '/usr/local/include/soundtouch'
>  /usr/bin/install -c -m 644 FIFOSampleBuffer.h FIFOSamplePipe.h SoundTouch.h STTypes.h BPMDetect.h soundtouch_config.h '/usr/local/include/soundtouch'
> Making install in source
> Making install in SoundTouch
>  ../../config/install-sh -c -d '/usr/local/lib'
>  /bin/sh ../../libtool   --mode=install /usr/bin/install -c   libSoundTouch.la '/usr/local/lib'
> libtool: install: /usr/bin/install -c .libs/libSoundTouch.lai /usr/local/lib/libSoundTouch.la
> libtool: install: /usr/bin/install -c .libs/libSoundTouch.a /usr/local/lib/libSoundTouch.a
> libtool: install: chmod 644 /usr/local/lib/libSoundTouch.a
> libtool: install: ranlib /usr/local/lib/libSoundTouch.a
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/libSoundTouch.a(mmx_optimized.o) has no symbols
> /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: /usr/local/lib/libSoundTouch.a(sse_optimized.o) has no symbols
> make[3]: Nothing to be done for`install-data-am'.
> Making install in SoundStretch
>  ../../config/install-sh -c -d '/usr/local/bin'
>   /bin/sh ../../libtool   --mode=install /usr/bin/install -c soundstretch '/usr/local/bin'
> libtool: install: /usr/bin/install -c soundstretch /usr/local/bin/soundstretch
> make[3]: Nothing to be done for `install-data-am'.
> make[3]: Nothing to be done for`install-exec-am'.
> make[3]: Nothing to be done for `install-data-am'.
> make[2]: Nothing to be done for`install-exec-am'.
>  config/install-sh -c -d '/usr/local/share/aclocal'
>  /usr/bin/install -c -m 644 soundtouch.m4 '/usr/local/share/aclocal'
>  config/install-sh -c -d '/usr/local/lib/pkgconfig'
>  /usr/bin/install -c -m 644 soundtouch-1.4.pc '/usr/local/lib/pkgconfig'
>  config/install-sh -c -d '/usr/local/doc/soundtouch'
>  /usr/bin/install -c -m 644 COPYING.TXT README.html '/usr/local/doc/soundtouch'

output of 'sudo python setup.py install':

> running install
> running build
> running build_ext
> running install_lib
> running install_egg_info
> Removing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysoundtouch-0.1.0-py2.7.egg-info
> Writing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysoundtouch-0.1.0-py2.7.egg-info

Does it having anything to do with my mac OS version? Mine is 10.11.4
Any advice? Thanks!

**Comment by jrising** [comment]
Hi @ssssophiaxd, I'll need more information to help you debug this.  Your `make` command would probably have some useful information, but you'll note that the one you sent me does not do any `make`-ing because it's already been compiled on your computer.  You should try cloning the repository and trying it again there.

It might also help to send me your /usr/local/lib/libSoundTouch.a file, since that's where the symbol is missing.

And, yes, it might be your OS version.  I've head of other problems related to libraries (not for soundtouch) in 10.11.

**Comment by ssssophiaxd** [comment]
[libSoundTouch.a.zip](https://github.com/jrising/pysoundtouch/files/577151/libSoundTouch.a.zip)
Thanks for getting back to me! Here is my libSoundTouch.a file.

**Comment by jrising** [comment]
I just checked this file and it has the function `__ZN10soundtouch10SoundTouch17setPitchSemiTonesEf` .  I then put it into my /usr/lib/local folder and ran `sudo python setup.py install` and then called `import soundtouch` and it worked properly.

Is it possible that you didn't re-run setup.py after fixing an error above?  What is the output of `sudo python setup.py install`?

**Comment by jrising** [comment]
You will probably need to delete the `build` directory to get `setup.py` to recompile the module: `sudo rm -r build`.

**Comment by ssssophiaxd** [comment]
here is the output of setup.py after I've removed the build directory:

> running install
> running build
> running build_ext
> building 'soundtouchmodule' extension
> creating build
> creating build/temp.macosx-10.6-intel-2.7
> creating build/temp.macosx-10.6-intel-2.7/src
> g++ -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DVERSION_MAJOR=0 -DVERSION_MINOR=1.0 -DVERSION="0.1.0" -I/usr/local/include/soundtouch -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/soundtouchmodule.c -o build/temp.macosx-10.6-intel-2.7/src/soundtouchmodule.o
> clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated
> In file included from src/soundtouchmodule.c:6:
> In file included from /usr/local/include/soundtouch/SoundTouch.h:75:
> In file included from /usr/local/include/soundtouch/FIFOSamplePipe.h:53:
> In file included from /usr/local/include/soundtouch/STTypes.h:47:
> /usr/local/include/soundtouch/soundtouch_config.h:79:9: warning: 'VERSION' macro
>       redefined [-Wmacro-redefined]
> #define VERSION "1.4.0"
>         ^
> <command line>:4:9: note: previous definition is here
> #define VERSION "0.1.0"
>         ^
> 1 warning generated.
> In file included from src/soundtouchmodule.c:6:
> In file included from /usr/local/include/soundtouch/SoundTouch.h:75:
> In file included from /usr/local/include/soundtouch/FIFOSamplePipe.h:53:
> In file included from /usr/local/include/soundtouch/STTypes.h:47:
> /usr/local/include/soundtouch/soundtouch_config.h:79:9: warning: 'VERSION' macro
>       redefined [-Wmacro-redefined]
> #define VERSION "1.4.0"
>         ^
> <command line>:4:9: note: previous definition is here
> #define VERSION "0.1.0"
>         ^
> 1 warning generated.
> g++ -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DVERSION_MAJOR=0 -DVERSION_MINOR=1.0 -DVERSION="0.1.0" -I/usr/local/include/soundtouch -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/pysoundtouch.cpp -o build/temp.macosx-10.6-intel-2.7/src/pysoundtouch.o
> In file included from src/pysoundtouch.cpp:13:
> src/pysoundtouch.h:9:9: warning: '__cplusplus' macro redefined
>       [-Wmacro-redefined]
> #define __cplusplus
>         ^
> <built-in>:330:9: note: previous definition is here
> #define __cplusplus 199711L
>         ^
> In file included from src/pysoundtouch.cpp:13:
> In file included from src/pysoundtouch.h:12:
> In file included from /usr/local/include/soundtouch/SoundTouch.h:75:
> In file included from /usr/local/include/soundtouch/FIFOSamplePipe.h:53:
> In file included from /usr/local/include/soundtouch/STTypes.h:47:
> /usr/local/include/soundtouch/soundtouch_config.h:79:9: warning: 'VERSION' macro
>       redefined [-Wmacro-redefined]
> #define VERSION "1.4.0"
>         ^
> <command line>:4:9: note: previous definition is here
> #define VERSION "0.1.0"
>         ^
> 2 warnings generated.
> In file included from src/pysoundtouch.cpp:13:
> src/pysoundtouch.h:9:9: warning: '__cplusplus' macro redefined
>       [-Wmacro-redefined]
> #define __cplusplus
>         ^
> <built-in>:333:9: note: previous definition is here
> #define __cplusplus 199711L
>         ^
> In file included from src/pysoundtouch.cpp:13:
> In file included from src/pysoundtouch.h:12:
> In file included from /usr/local/include/soundtouch/SoundTouch.h:75:
> In file included from /usr/local/include/soundtouch/FIFOSamplePipe.h:53:
> In file included from /usr/local/include/soundtouch/STTypes.h:47:
> /usr/local/include/soundtouch/soundtouch_config.h:79:9: warning: 'VERSION' macro
>       redefined [-Wmacro-redefined]
> #define VERSION "1.4.0"
>         ^
> <command line>:4:9: note: previous definition is here
> #define VERSION "0.1.0"
>         ^
> 2 warnings generated.
> g++ -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DVERSION_MAJOR=0 -DVERSION_MINOR=1.0 -DVERSION="0.1.0" -I/usr/local/include/soundtouch -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/pybpmdetect.cpp -o build/temp.macosx-10.6-intel-2.7/src/pybpmdetect.o
> In file included from src/pybpmdetect.cpp:13:
> In file included from src/pybpmdetect.h:10:
> In file included from /usr/local/include/soundtouch/BPMDetect.h:60:
> In file included from /usr/local/include/soundtouch/STTypes.h:47:
> /usr/local/include/soundtouch/soundtouch_config.h:79:9: warning: 'VERSION' macro
>       redefined [-Wmacro-redefined]
> #define VERSION "1.4.0"
>         ^
> <command line>:4:9: note: previous definition is here
> #define VERSION "0.1.0"
>         ^
> 1 warning generated.
> In file included from src/pybpmdetect.cpp:13:
> In file included from src/pybpmdetect.h:10:
> In file included from /usr/local/include/soundtouch/BPMDetect.h:60:
> In file included from /usr/local/include/soundtouch/STTypes.h:47:
> /usr/local/include/soundtouch/soundtouch_config.h:79:9: warning: 'VERSION' macro
>       redefined [-Wmacro-redefined]
> #define VERSION "1.4.0"
>         ^
> <command line>:4:9: note: previous definition is here
> #define VERSION "0.1.0"
>         ^
> 1 warning generated.
> g++ -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DVERSION_MAJOR=0 -DVERSION_MINOR=1.0 -DVERSION="0.1.0" -I/usr/local/include/soundtouch -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/WavFile.cpp -o build/temp.macosx-10.6-intel-2.7/src/WavFile.o
> creating build/lib.macosx-10.6-intel-2.7
> g++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-intel-2.7/src/soundtouchmodule.o build/temp.macosx-10.6-intel-2.7/src/pysoundtouch.o build/temp.macosx-10.6-intel-2.7/src/pybpmdetect.o build/temp.macosx-10.6-intel-2.7/src/WavFile.o -L/usr/local/lib -lSoundTouch -o build/lib.macosx-10.6-intel-2.7/soundtouchmodule.so
> ld: warning: ignoring file /usr/local/lib/libSoundTouch.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libSoundTouch.dylib
> running install_lib
> copying build/lib.macosx-10.6-intel-2.7/soundtouchmodule.so -> /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
> running install_egg_info
> Removing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysoundtouch-0.1.0-py2.7.egg-info
> Writing /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pysoundtouch-0.1.0-py2.7.egg-info

Is it because of the warnings? 
Thanks again for helping!

**Comment by ssssophiaxd** [comment]
Hi @jrising , sorry for bothering you for this long, but can you give me any reply regarding the output of my setup.py I posted above? Many thanks!

**Comment by jrising** [comment]
My best guess at this point is that it has to do with the `.dylib` file you have in /usr/local/lib:

```
ld: warning: ignoring file /usr/local/lib/libSoundTouch.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libSoundTouch.dylib
```

When I run the install commands, I don't get a `.dylib` file.  It could be that this is from a previous compiling of the library and that it doesn't have the integer samples that the library needs.  You could try removing all of the libSoundTouch files in /usr/local/lib (`sudo rm /usr/local/lib/libSoundTouch.*`), and then start over from the `./boostrap` command.

**Comment by ssssophiaxd** [comment]
@jrising Thank you so much for the help! Finally everything worked!!!!
Thanks again for answering my silly questions <3
